
## these must be changed.

LIBDIR = $(SRCDIR)
FTPROOT = /home/ftp

INCLIB = -I$(LIBDIR)

INSTALL = install -m755 -o root -g root

## these prolly doesnt need to be changed.

CC = gcc -O0 -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-all -DSSP

## these should not be changed.

%.o: %.c
	$(CC) -c $< $(INCLIB) $(DEFS)

