
## these must be changed.

LIBDIR = $(SRCDIR)
FTPROOT = /export/f00

INCLIB = -I$(LIBDIR)

INSTALL = install -m755 -o root -g root

## these prolly doesnt need to be changed.

CC = gcc -O2

## these should not be changed.

%.o: %.c
	$(CC) -c $< $(INCLIB) $(DEFS)


## this is for building release out of the cvs.
RELEASEDIR = $(HOME)/foo/release
RELEASEFILE = $(HOME)/foo/foo-tools-latest.tar.gz
