
## these must be changed.

LIBDIR = $(SRCDIR)
FTPROOT = /glftpd

INCLIB = -I$(LIBDIR)

INSTALL = install -m755 -o root -g root

## these prolly doesnt need to be changed.

CC = gcc -O2

## these should not be changed.

%.o: %.c
	$(CC) -c $< $(INCLIB) $(DEFS)

